last_update = 1676034630637
api_url = "https://api.playit.cloud/agent"
ping_target_addresses = ["23.133.216.1:5530", "ping.ply.gg"]
control_address = "control.ply.gg"
refresh_from_api = true
api_refresh_rate = 5000
ping_interval = 5000
secret_key = "6f6b9a9323d5d00e95badf17dd7bc61140316fa40383025858bb4760ca8232f5"

[[mappings]]
name = "mcpe (19132)"
proto = "udp"
tunnel_ip = "147.185.221.180"
tunnel_from_port = 54341
local_port = 19132

[[mappings]]
name = "mc (25565)"
proto = "tcp"
tunnel_ip = "147.185.221.194"
tunnel_from_port = 52591
local_port = 25565
